"""Sync Models

Revision ID: d99ffbb0152d
Revises: 0002
Create Date: 2026-06-09 15:52:55.711756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd99ffbb0152d'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'sources',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('chat_messages', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.drop_constraint('chat_messages_ibfk_1', 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'tokens_used')
    op.drop_column('chat_messages', 'excel_updates')
    op.drop_column('chat_messages', 'thinking')
    op.alter_column('chat_sessions', 'title',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('chat_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('documents', 'filename',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('documents', 'original_filename',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('documents', 'storage_path',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('documents', 'file_size',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'is_excel',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('documents', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('documents', 'status',
               existing_type=mysql.ENUM('PENDING', 'PROCESSING', 'READY', 'FAILED'),
               type_=sa.String(length=20),
               nullable=True)
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'document_type')
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'uploaded_at')
    op.drop_column('documents', 'metadata')
    op.drop_column('documents', 'updated_at')
    op.drop_index('ix_excel_meta_doc_id', table_name='excel_metadata')
    op.drop_index('ix_excel_meta_session_id', table_name='excel_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_excel_meta_session_id', 'excel_metadata', ['session_id'], unique=False)
    op.create_index('ix_excel_meta_doc_id', 'excel_metadata', ['doc_id'], unique=False)
    op.add_column('documents', sa.Column('updated_at', mysql.DATETIME(), nullable=False))
    op.add_column('documents', sa.Column('metadata', mysql.JSON(), nullable=True))
    op.add_column('documents', sa.Column('uploaded_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('documents', sa.Column('error_message', mysql.TEXT(), nullable=True))
    op.add_column('documents', sa.Column('document_type', mysql.ENUM('document', 'spreadsheet'), server_default=sa.text("'document'"), nullable=False))
    op.add_column('documents', sa.Column('page_count', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('documents', 'status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('PENDING', 'PROCESSING', 'READY', 'FAILED'),
               nullable=False)
    op.alter_column('documents', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('documents', 'is_excel',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('documents', 'file_size',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'storage_path',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=False)
    op.alter_column('documents', 'original_filename',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=512),
               nullable=False)
    op.alter_column('documents', 'filename',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('chat_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=True)
    op.add_column('chat_messages', sa.Column('thinking', mysql.TEXT(), nullable=True))
    op.add_column('chat_messages', sa.Column('excel_updates', mysql.JSON(), nullable=True))
    op.add_column('chat_messages', sa.Column('tokens_used', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('chat_messages_ibfk_1', 'chat_messages', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.alter_column('chat_messages', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('chat_messages', 'sources',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###
