"""Revert uploaded_at

Revision ID: e5e4bb6fb713
Revises: d99ffbb0152d
Create Date: 2026-06-09 15:57:48.868281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e5e4bb6fb713'
down_revision: Union[str, None] = 'd99ffbb0152d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('documents', 'created_at')
    op.drop_index('ix_excel_meta_doc_id', table_name='excel_metadata')
    op.drop_index('ix_excel_meta_session_id', table_name='excel_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_excel_meta_session_id', 'excel_metadata', ['session_id'], unique=False)
    op.create_index('ix_excel_meta_doc_id', 'excel_metadata', ['doc_id'], unique=False)
    op.add_column('documents', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.drop_column('documents', 'uploaded_at')
    # ### end Alembic commands ###
